version: '3.9'

services:

  db:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes: 
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: db_v1
    container_name: postgres_db1

  Auth:
    build:
      context: Auth
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - Auth/.env.uat
    container_name: Auth
    depends_on:
      - db
  Project:
    build:
      context: Project
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
      - Project/.env.uat
    container_name: Project

  nginxgw:
    image: nginx
    command: service nginx start
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  db_data: